# This contains params to be used by the stages to train or predict

hyper_parameters:
  split_ratio: 0.3
  random_state: 42



model_params:
  ElasticNet:
    # alpha: 0.5
    # l1_ratio: 0.5
    alpha: 0.7
    l1_ratio: 0.5


