# It contains all the configs required in the project

data_source: http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts:
  ARTIFACTS_DIR: artifacts
  RAW_DATA_DIR: raw_data
  RAW_DATA_FILE: main.csv
  TRAINED_MODEL_DIR: model
  MODEL_FILE_NAME: model.pkl
  SPLIT_DATA_DIR: split_data
  TRAIN_DATA: train.csv
  TEST_DATA: test.csv

scores: scores.json





#   BASE_MODEL_NAME: base_model.h5
#   UPDATED_BASE_MODEL_NAME: updated_base_model.h5
#   CHECKPOINT_DIR: checkpoints
#   BASE_LOG_DIR: base_model_dir
#   TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
#   CALLBACKS_DIR: callbacks

# source_download_dirs:
#   - path_to_data_1
#   - path_to_data_1

# local_data_dirs:
#   - path_to_local_data_1
#   - path_to_local_data_2
